In [1]:
import numpy as np
import pandas as pd

In [2]:
measures=pd.read_csv('measurements.csv', names=['x', 'y', 'z'])
truths = pd.read_csv('groundtruth.csv', names=['x', 'y', 'z'])

In [3]:
# it will fit the line using square of least square
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(measures, truths)
print('Matrix A: \n', lr.coef_ )

Matrix A: 
 [[ 9.99389038e-01  3.49017510e-02  1.12915901e-06]
 [-3.48994183e-02  9.99390665e-01 -3.09984206e-07]
 [-1.90617420e-05  3.69475621e-06  8.33268359e-01]]


In [4]:
print('b column vector: \n', lr.intercept_ )

b column vector: 
 [-0.18939257  0.30679377 -0.00069183]


<h4> Part b </h4>

In [5]:
# Applying the correction function on measurements
corrections = lr.predict(measures)
error = np.sum(np.sum(np.power(truths-corrections, 2)))
print('Error after correction: ', error)

Error after correction:  0.030335501238018352


The error is exactly not zero, becuase actually least square minimization offers the best fit line and it is alwasy difficult to obtain the exact mapping becuase of the number of reasons that may include errors in the sensor reading (both human and instrument), sometimes outlier exists too.

<h4>Part c</h4>

Correction is sacler, as we are just multiplying the original values with some scaler value and then adding a value(from b) in it. So, it is just involves scaling the original values. It doesn't involve any kind of axis or rotations at all.